spring.application.name=multithreaded-web-crawler

server.port=8080


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/crawler}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Yogeshbhatt@2003}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# FLYWAY
# =========================================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true


# =========================================================
# REDIS
# =========================================================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.connect-timeout=5s
spring.data.redis.timeout=5s


# =========================================================
# DISTRIBUTED LOCK
# =========================================================

app.distributed-lock.expiration-seconds=10


# =========================================================
# RATE LIMITING
# =========================================================

app.rate-limit.capacity=3
app.rate-limit.refill-tokens=1
app.rate-limit.refill-duration-seconds=1


# =========================================================
# CRAWLER
# =========================================================

crawler.max-depth=3
crawler.max-pages=100
crawler.request-timeout-seconds=10
crawler.user-agent=MultithreadedWebCrawler/1.0


# =========================================================
# REDIS CRAWLER STREAM
# =========================================================

crawler.redis.stream-key=crawler:stream
crawler.redis.consumer-group=crawler-group
crawler.redis.visited-set-key=crawler:visited
crawler.redis.recovery-idle-seconds=30
crawler.redis.recovery-interval-ms=10000


# =========================================================
# LOGGING
# =========================================================

logging.level.com.crawler=INFO
logging.level.org.springframework.data.redis=INFO
logging.level.org.flywaydb=INFO